### ISSUE TITLE
Fix rtd build error

### ISSUE THREAD

**Issue by skyoo2003** [skyoo2003/kakaowork-py#95]
Perhaps it's because the dependency resolution didn't work properly...

https://readthedocs.org/projects/kakaowork-py/builds/14243283/

```
Running Sphinx v4.1.1

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/kakaowork-py/envs/latest/lib/python3.7/site-packages/sphinx/config.py", line 327, in eval_config_file
    exec(code, namespace)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kakaowork-py/checkouts/latest/docs/conf.py", line 18, in <module>
    from kakaowork import __version__  # noqa: E402
  File "/home/docs/checkouts/readthedocs.org/user_builds/kakaowork-py/checkouts/latest/kakaowork/__init__.py", line 8, in <module>
    from kakaowork.client import (Kakaowork, AsyncKakaowork)
  File "/home/docs/checkouts/readthedocs.org/user_builds/kakaowork-py/checkouts/latest/kakaowork/client.py", line 5, in <module>
    import aiosonic
  File "/home/docs/checkouts/readthedocs.org/user_builds/kakaowork-py/envs/latest/lib/python3.7/site-packages/aiosonic/__init__.py", line 31, in <module>
    import chardet
ModuleNotFoundError: No module named 'chardet'
```

**Comment by skyoo2003** [comment]
Fixed dependencies resolution regex of aiosonic. Just wait for the next release without any changes
